# Ruff configuration file for FastAPI project
[lint]
ignore = [
    "B008",  # Do not perform function call `Depends` in argument defaults
    "BLE001" # Do not catch blind exception: `Exception` in seed.py
]
